server:
  port: 8090
spring:
  application:
    name: uplpoad-s3-sample
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/design_product_service?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 123456

aws:
  s3:
    accessKey: accesskey
    secretKey: secretkey
    region: region
    bucket: bucket