server:
  port: 8090
spring:
  application:
    name: uplpoad-s3-sample
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service_hpdesign?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 123456

#    setup file size request
  servlet:
    multipart:
      max-request-size: 2073742019
      max-file-size: 2073742019

aws:
  s3:
    accessKey: AKIAWWFSTK4E67RZA3NC
    secretKey: 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
    region: ap-southeast-1
    bucket: unity-test-1